### ISSUE TITLE
FPBioImage on a linux webserver? 

### ISSUE THREAD

**Issue by mkmat** [fpBioImage/assets#2]
I installed the Template-Website on a linux webserver (64 bit). The javascript does not seem to start, I can just see the website without embedded 3D graphics. Should FPBioImage work on a linux server?

**Comment by mfantham** [comment]
There's a really early version of the software hosted at
http://mjf74.user.srcf.net , which is on an Ubuntu server. So yes, it
should work just fine on a Linux box.

You may have problems running it locally (ie just browsing to the html
file) since the PNG image files have to be downloaded from a server, so
make sure you're running a local server and navigate to the localhost
address of the webpage. Something like jekyll serve can help with this.

Please do post another message if you're still having problems.

**Comment by mfantham** [comment]
Check out this useful web resource for more info: 

https://threejs.org/docs/#Manual/Getting_Started/How_to_run_things_locally

Let me know if this sorted it, and please close the issue if so!

**Comment by mkmat** [comment]
Thank you for your response, it is helpful. I probably forgot to mention that I copied all files to an institutional linux apache webserver, because I want to share the images. I don't want to run anything locally on my PC. I could now imagine that the server has javascript protection settings, that I cannot view at present, I hope the problem originates from here and I'll close this issue if it was solved this way.

**Comment by mfantham** [comment]
That certainly sounds possible. You can open up a developers console in (eg) Chrome (ctrl+shift+J) which might help more with diagnosis. 

I assume you checked out the sharing guide? https://www.youtube.com/watch?v=sdEQ59pYzSY

I'm currently finalising an imageJ/Icy plugin which should make the website creation process easier.

**Comment by mkmat** [comment]
Yes I know the nice sharing guide! It especially helped me to find out that the data format required for FPBioimage is a simple sequence of numbered png images, and not any of the remaining 3D image data formats that are in use. This is nowhere written, but it was fortunately visible in the movie. Information missing from the movie is that the Template contains a stack called 'wavefunction' and that it can (probably) be used to test the installation without creating your own stack. As sequences of png images can be created using many tools, I personally do not need imageJ. Once I'll have solved the still open java issue, I can provide you with a script (or website) that generates the FPBioimage website to visualize 3D matrices (matlab or ascii i.e. c /fortran/etc format), without the need to manually call software. The png sequence can also be created (and stored efficiently) from a mpg-movie via 'convert'. Thanks again for your help, I am looking forward getting this running, and if so, it will be of great help for me.

**Comment by mfantham** [comment]
Yes - the decision to use PNG images was for good file compression for fast download times - TIFF stacks and other 3D formats can quickly run into GB file sizes, making them impractical for quickly sharing an interactive view of your data on the web. And as you rightly point out, a PNG stack can be made from a wide variety of programs - imageJ was chosen for the guide, as it seems to be the most popular in my field. (Personally I actually use [Icy](http://icy.bioimageanalysis.org/) to prep my data.)

The text version of the [sharing guide](http://fpb.ceb.cam.ac.uk/sharingGuide/) explains PNG image preparation in written form. I will try to make this clearer. Many thanks for your feedback! 

Let me know of any progress on the javascript issue.

**Comment by mkmat** [comment]
It is now running properly without adjustment, the problem was an apache setting for java scripts. Thanks again for your quick response. I came across another, unrelated issue, I'll put it in a separate 'issue'.
